name: Enforce Branch Naming Convention

on:
  push:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce branch naming convention
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ ! "$BRANCH_NAME" =~ ^feature\/.+$ ]]; then
            echo "❌ Branch name '$BRANCH_NAME' does not follow the 'feature/<feature_name>' convention."
            exit 1
          fi
